function DiseaseEnrichResults = importDiseaseEnrichfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DISEASEENRICHRESULTS = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  DISEASEENRICHRESULTS = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  DiseaseEnrichResults = importfile("C:\Users\Stuart\Documents\ThalamicGradients\Project_wg_result1665153115\enrichment_results_wg_result1665153115.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 07-Nov-2022 19:10:39

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["geneSet", "description", "link", "size", "overlap", "expect", "enrichmentRatio", "pValue", "FDR", "overlapId", "database", "enriched_genes"];
opts.VariableTypes = ["double", "char", "double", "double", "double", "double", "double", "double", "double", "char", "char", "char"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["description", "overlapId", "database", "enriched_genes"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["description", "overlapId", "database", "enriched_genes"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["geneSet", "link"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["geneSet", "link"], "ThousandsSeparator", ",");

% Import the data
DiseaseEnrichResults = readtable(filename, opts);

end