%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Stuart\Documents\ThalamicGradients\receptor2tracer.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 14-Apr-2022 11:28:12

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A1:D39";

% Specify column names and types
opts.VariableNames = ["HT1a", "cumi", "hc8", "beliveau"];
opts.VariableTypes = ["char", "char", "char", "char"];

% Specify variable properties
opts = setvaropts(opts, ["HT1a", "cumi", "hc8", "beliveau"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["HT1a", "cumi", "hc8", "beliveau"], "EmptyFieldRule", "auto");

% Import the data
receptor2tracer_map = readtable("C:\Users\Stuart\Documents\ThalamicGradients\receptor2tracer.xlsx", opts, "UseExcel", false);

%% Convert to output type
receptor2tracer_map = table2cell(receptor2tracer_map);
numIdx = cellfun(@(x) ~isnan(str2double(x)), receptor2tracer_map);
receptor2tracer_map(numIdx) = cellfun(@(x) {str2double(x)}, receptor2tracer_map(numIdx));

%% Clear temporary variables
clear opts